server:
  port: 8761

ead:
  serviceRegistry:
    username: '{cipher}AgB/zLiRGZ9RvldeM5WxxMCrn8znZD6pMLTKlOkvfRqn6BqWcgoPPfzz6n91W2HK45b0NKkSV4QUlQwNqLBC5Sw8ItceeTX1LNsA++YimaE1yFD56UJX5agy9z33mW3dy3GTGW1cMa1OjmVbaNaLW45KXsjuTLyKad6Mdzx7IQ5l0AyRkzoAvnY4+ByrmuLYblmZ9U3UFKNY1GzqeYyxGUp33gZRgUJcFmik4TIs9RVInVbYyQmDplvgndoYEVNev1RzGJx1IqNHSJI0lHDsMBVIHcqVwcAzD0hbMklAag+mPiInaBzIPVqgm1gmpJc29Hb3PcrWCJEh3wOjgRHnJcDhAnPQgtiNcDqv46zFoxHPSD3fxJDCUeXu21w0gCTjV+BxA/6Oy+vhKe0/8Z5KKPIKTynu1y0ywieTZjiB0P6qFkWHrzucH9m7DTGlqm6v6/1vckS7Xbi+PflgyOUKxHR+pVuMkndUosYcZHyYaZBs67rlvGGE4DMfKk1LU3luzuRK9qW14GhYG6K3ZXH7SZLRCQ9g7g2QtuzkUw23xYDJx77D+aAsy2AgDtTYsUGu9bLuAhf1e18voSMAZbpSjIO+fubgbgjQto8oMgwCyHvUrFzhtI5jpD3MmEpVfsxtVfI+VMNxOikRqSU4RnSwcmRiQK/nivLr4T1zPRVSXuXQqq9QMeCAHujLBFw2fS2PSOXuqcl38TA4VjndHMIs1Ee4'
    password: '{cipher}AgACR6ZZ0dAGq8lSAlOZlokb+M10jeZ1PfRllQacb+6REZusdeFfzgQ25pKJ+CU09PEKCzsd3h4eMaBM3nRkHGw1BeCJ3WLY+L2shaYXrui8izykpED3MCvfc/Y9b0Xsh4tx9zShdjBACjVijU70G7PSNM9C2SVYPoS0RDHz2C2gXyZ9WL1Cc6qP2r7lOG+WBtwKQU025rlysbvNjUzqtsok5pAXMjJsPO9ClyaXedtuQp+yHYEuSn+0TSkWhF+AzrI/mC9cwcG9qMRgsOqJkDzppc0pBVT+xsu7CaWBaXNeQctD15S0no6Awx5K5AbEbEOiojdEp9Q5AEeblzYk2zQYO7ezJdZEyZcGBvyw1Bk9xAWii1sId+F433l02C1WBOMg42njQX0n16aKE9ixaqsW71paO6caAjMyx9RVGmQ/u8IhTXGj/rLWeHfjs2Mau7rFnGYBOL18hZ23IgI50Tu+7rUlDGkf56TeFX7tC65DN+RXqsDr2FT5M8iS2lDdMz0dLx6/gUICzm5lGQiDcTWWInUGH2ezD1/szxhPiVIYFDCZ0AJJcKodJV7hsVyg/GqUXIspHx/8VH7ZdarBxi7e/GeZ1J7dVGYhpi/6rpJDcne0AtyephzK57Dp5JQxXSl2yFXt0HolbP339F9HGMvDzL0qbOJRtFhdZ1yl/yTSVq4ToqIlWycI5by0keepdGJJJWGle2dmDXvoElPbg+++'

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: 'http://${ead.serviceRegistry.username}:${ead.serviceRegistry.password}@localhost:8761/eureka'
